name: Sync Push Testing

on:
  push:
    branches:
     [ GitManagement ]
        
permissions:
  contents: write
  pull-requests: write        


jobs:
  sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3
      with:
        ref: GitManagement

    - name: Configure git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
    
    - name: Add destination repo as remote
      run: |
        git remote add destination https://${{ secrets.TOKEN }}@github.com/${{ secrets.TARGET_REPO }}.git

    - name: Push GitManagement to destination intermediate branch
      run: |
        git push destination GitManagement:refs/heads/${{ secrets.INTERMEDIATE_BRANCH }} --force
        
    - name: Create pull request on destination repo
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.TOKEN }}
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_branch: main
        repository: ${{ secrets.TARGET_REPO }}

